database:
  con: sqlite:///users.db

path:
  work_lmt: /home/lmt/work_lmt
  prefix: /pipeline_web/

session:
  init_session: session-0

ssh:
  username: lmthelpdesk_umass_edu
  hostname: unity.rc.umass.edu

pipeline_user:
  username: pipeline_web

github:
  api_url: https://api.github.com/orgs/lmtoy/repos
  repo_prefix: lmtoy_

authentication:
  csv_file: lmt_archive_user_info_20250702.csv
  csv_path: .


