database:
  con: sqlite:///users.db

path:
  work_lmt: /home/lmt/work_lmt
  data_lmt: /home/lmt/data_lmt
  prefix: /pipeline_web/
  python_path: /home/lmt/LMT_projects/lmt_web_lite/env/bin/python3.9
  lmtoy_path: /home/lmt/LMT_projects/lmt_web_lite/lmtoy_lite


session:
  init_session: session-0

ssh:
  username: lmthelpdesk_umass_edu
  hostname: unity.rc.umass.edu

2023-S1-US-17:
  email: xia.summer.huang@gmail.com
  #instrument: rsr
  instrument: sequoia

