database:
  con: sqlite:///users.db

path:
  work_lmt: /home/lmt/work_lmt
  prefix: /pipeline_web/

session:
  init_session: session-0

ssh:
  username: lmthelpdesk_umass_edu
  hostname: unity.rc.umass.edu

pipeline_user:
  username: pipeline_web


